### ISSUE TITLE
How to disable input field labels on sign up and log in page?

### ISSUE THREAD

**Issue by engincandy** [pennersr/django-allauth#1803]
What is the easiest way to disable the input labels on the sign up and log in page?

**Comment by FlowFX** [comment]
The easiest?
```css
label {
    display: none;
}
```
;)
